# Generated by Django 3.0.2 on 2020-06-01 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('bio', models.TextField(default='nothing to about..', max_length=150)),
                ('email', models.EmailField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('avatar', models.ImageField(default='avatar.png', upload_to='avatars/')),
                ('profession', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.DateTimeField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
